// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package model

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Changelog struct {
	ID               int32
	Uuid             pgtype.UUID
	ObjectName       string
	ObjectID         int32
	ParentObjectName pgtype.Text
	ParentObjectID   pgtype.Int4
	Operation        string
	FieldName        string
	OldValue         pgtype.Text
	NewValue         pgtype.Text
	CreatedAt        pgtype.Timestamp
}

type MeasurementUnit struct {
	ID                 int32
	Uuid               pgtype.UUID
	ReferenceUnitID    pgtype.Int4
	ReferenceUnitValue pgtype.Numeric
	Name               string
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
	DeletedAt          pgtype.Timestamp
}

type Product struct {
	ID                int32
	Uuid              pgtype.UUID
	MeasurementUnitID int32
	Name              string
	Barcode           string
	MeasurementValue  pgtype.Numeric
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
	DeletedAt         pgtype.Timestamp
}

type Recipe struct {
	ID        int32
	Uuid      pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type RecipeProduct struct {
	ID        int32
	RecipeID  int32
	ProductID int32
	Quantity  pgtype.Numeric
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type RecipeSellingHistory struct {
	ID           int32
	RecipeID     int32
	CostPrice    pgtype.Numeric
	SellingPrice pgtype.Numeric
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
}

type StockHistory struct {
	ID               int32
	StockOperationID int32
	ProductID        int32
	Quantity         pgtype.Numeric
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
	DeletedAt        pgtype.Timestamp
}

type StockOperation struct {
	ID        int32
	Uuid      pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}
