// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package model

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRecipe = `-- name: GetRecipe :one
SELECT  recipe.id, recipe.uuid, recipe.name, recipe.created_at, recipe.updated_at, recipe.deleted_at,
        product.id, product.uuid, product.measurement_unit_id, product.name, product.barcode, product.measurement_value, product.created_at, product.updated_at, product.deleted_at,
        measurement_unit.id, measurement_unit.uuid, measurement_unit.reference_unit_id, measurement_unit.reference_unit_value, measurement_unit.name, measurement_unit.created_at, measurement_unit.updated_at, measurement_unit.deleted_at
FROM    recipe
JOIN    product ON recipe.product_id = product.id
JOIN    measurement_unit ON product.measurement_unit_id = measurement_unit.id
WHERE   recipe.id = $1
LIMIT   1
`

type GetRecipeRow struct {
	ID                 int32
	Uuid               pgtype.UUID
	Name               string
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
	DeletedAt          pgtype.Timestamp
	ID_2               int32
	Uuid_2             pgtype.UUID
	MeasurementUnitID  int32
	Name_2             string
	Barcode            string
	MeasurementValue   pgtype.Numeric
	CreatedAt_2        pgtype.Timestamp
	UpdatedAt_2        pgtype.Timestamp
	DeletedAt_2        pgtype.Timestamp
	ID_3               int32
	Uuid_3             pgtype.UUID
	ReferenceUnitID    pgtype.Int4
	ReferenceUnitValue pgtype.Numeric
	Name_3             string
	CreatedAt_3        pgtype.Timestamp
	UpdatedAt_3        pgtype.Timestamp
	DeletedAt_3        pgtype.Timestamp
}

func (q *Queries) GetRecipe(ctx context.Context, id int32) (GetRecipeRow, error) {
	row := q.db.QueryRow(ctx, getRecipe, id)
	var i GetRecipeRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ID_2,
		&i.Uuid_2,
		&i.MeasurementUnitID,
		&i.Name_2,
		&i.Barcode,
		&i.MeasurementValue,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.DeletedAt_2,
		&i.ID_3,
		&i.Uuid_3,
		&i.ReferenceUnitID,
		&i.ReferenceUnitValue,
		&i.Name_3,
		&i.CreatedAt_3,
		&i.UpdatedAt_3,
		&i.DeletedAt_3,
	)
	return i, err
}
